[files]
[files.input]
# paths to files containing the input data to be processed
data = [
        "input/chunk-0.csv",
        "input/chunk-1.csv",
        "input/chunk-2.csv",
    ]

# path to file containing sections information
sections = "input/sections.txt"

# path to file containing critical points information
points = "input/critical-points.csv"

# path to file variants information.
variants = "input/variant-sections.txt"

[files.output]
# path where the results related to sections will be saved
sections = "input/results-sections.csv"

# path where the results related to points will be saved
points = "input/results-points.csv"

[analysis]
# start date and time for the analysis period
from = 2024-05-01T00:00:00

# end date and time for the analysis period
to = 2024-05-31T23:00:00

# time interval (in seconds) for analysis
interval = 3600

# if save processed results or not
save_results = true
